microsoft/vscode-test

- lib/runTest.ts
This makes `runTests()` similar to [vscode-extension-vscode: bin/test][1].
[1]: https://github.com/Microsoft/vscode-extension-vscode/blob/113b669216ab378da6502daf6375a3e6a620e3fa/bin/test#L43
> feat(runTests): support specifying the locale

- lib/util.ts
This PR fixes #4 
I'm using proxy setting like the below
```sh
$ cat ~/.npmrc
proxy=http://xx.xx.xxx.xx:8080/
https-proxy=http://xx.xx.xxx.xx:8080/
```
But vscode-test is not using `HttpsProxyAgent` to request list of stable release version, when proxy address is not started with `https`.
I think it needs to use `HttpsProxyAgent` because it needs to access https protocol url.
- stable release version url: https://update.code.visualstudio.com/api/releases/stable
To solve this problem, i refer given `url` to select proper ProxyAgent.
If you got any issue, feel free to contact me :smile:
> Refer url protocol and npm config to use appropriate proxy agent 

- README.md
The README specifies `node > 8.x` (strictly greater than 8.x), but the `package.json` specifies `node >= 8.9.3` (greater than or equal to 8.9.3):
https://github.com/microsoft/vscode-test/blob/b8813110b229fa1a524650c16ec521df42b7893d/package.json#L10-L12
I use node 8 so this was important to me that node 8 is supported.
Thanks!
> Fix node dependency version

- README.md
This updates the example code in README.md to match the [sample/test/runTest.ts](https://github.com/microsoft/vscode-test/blob/669ba6db18fbd36474d2a9ff520ab71d542b25c5/sample/test/runTest.ts) (and thus the current API).
> Update example code to match current API

- lib/runTest.ts
While investigating a SIGSEGV which intermittently terminates an
invocation of
```
.vscode-test/vscode-1.42.1/VSCode-linux-x64/code
--disable-extensions --extensionDevelopmentPath=$DEVELOPMENT_PATH \
--extensionTestsPath=$EXTENSION_TESTS_PATH/index;
```
spawned by `vscode-test`, I found it desirable to determine whether
the test runner was terminating due to test failures or that SIGSEGV
signal. In general, I think it would be useful for the `vscode-test`
client to have this information.
The [documentation][1] says:
```
If the process terminated due to receipt of a signal, signal is the
string name of the signal, otherwise null. One of the two [i.e. `code`
and `signal`] will always be non-null.
```
[1]: https://nodejs.org/api/child_process.html#child_process_event_exit
> runTests: propagate signal when subprocess terminated

- lib/download.ts
> fix: don't write progress report when output is not connected to tty

- lib/runTest.ts
The implementation of `runTests` returns a promise that, in case of failure, invokes **both** the `resolve` and `reject` callbacks. It looks like a bug and this PR fixes that.
https://github.com/microsoft/vscode-test/blob/8e8d7a872ff6f01f818ee031fd5704233442f663/lib/runTest.ts#L182-L189
> Avoid calling resolve after reject

- lib/download.test.ts
- lib/download.ts
- lib/runTest.ts
- lib/util.ts
- package.json
- vitest.config.ts
- yarn.lock
We previously duplicated the "architecture" in the "platform" field.
This PR unifies that into the single "platform" field (which was already
exposed by consumer to specify the architecture for some things) which
resolves the issue.
Also pulls in vitest to add tests that the download is successful on
all platforms.
Fixes https://github.com/microsoft/vscode-test/issues/141
> fix: incorrect platform used on arm64 Linux

- lib/runTest.ts
Allow array for extensionDevelopmentPath as discussed in #147
> Allow array for extensionDevelopmentPath

- lib/download.ts
- lib/util.ts
- sample/test/runTest.ts
Useful when the latest insiders is broken, and you can't test against stable.
If you are ok with this feature, I will add docs and tests
> Enable downloading a particular insider commit.

- CHANGELOG.md
- lib/download.ts
- lib/util.ts
- package.json
While hiking/biking/boating on vacation, I often would not have network access, which prevented tests from running unless I manually specified a version.
Instead, if `stable` is given, the update service is inaccessible, and there is a stable version already downloaded on-disk, emit a warning and use that.
Fixes https://github.com/microsoft/vscode-test/issues/51
> feat: use existing local installs if update service is inaccessible

- lib/download.ts
`(string & {})` is correct
[ts playground](https://www.typescriptlang.org/play?ssl=6&ssc=1&pln=7&pc=1#code/C4TwDgpgBAysBOBLAdgcwDKOBeBDANgKrKID2yAPACpQQAe2yAJgM5SEA07UAvFCwhSoAfLyg0APlAAUhKADIoAbwC+ASgDcAKC2hIsQWkzY8REuQBiiOhCbVaDCMzYCkaUX0kzXQhcvXaWgDG5AJQAGakpABcBm4YWDgExGSUAOS4aR5QaWnBocARUQCMsXDxxklmqVY2dhlZYrlaQA)
> Fix completions of version and platform

- lib/download.test.ts
- lib/download.ts
- lib/util.ts
- package.json
- yarn.lock
Automatically use the latest version of VS Code that satisfies all constraints in `engines.vscode` in `package.json`. (But only use Insiders if no stable build satisfies the constraints.)
This also lets users pass `X.Y.Z-insider` to runTests, where previously it was only possible to request the latest Insiders version.
Fixes #176
> feat: automatically use vscode version matching engine

- CHANGELOG.md
- lib/download.ts
- package.json
I'm using this package for some smoke tests involving the CLI. Slight tweak is necessary.
> fix: download cli correctly for linux

- lib/util.ts
121fe1f6ecba08a22d7ae753c19a8bef5e7ded7c accidentally changed this from 'insiders' to 'insider'. As a result, if a downloaded insiders build is found, it is never re-downloaded
> Fix insiders version string check

- CHANGELOG.md
- lib/download.ts
- package.json
Fixes #233, which Andrea ran into when testing.
Instead of staging and renaming, which tends to fail on Windows, write a 'completed' file when the install is done.
> fix: avoid faulty rename when installing

- sample/package.json
- sample/src/test/suite/index.ts
- sample/src/test/suite2/index.ts
- sample/yarn.lock
- update `glob` version
- remove `@types/glob`
The current `glob` library used in the test code has been updated to use `promise` instead of `callback` starting from version `v9.0.0`.  But example code are using `v7.x.x`. It is little bit old and may confusing new developer.
And, the glob 9+ supports TypeScript, there is no need to install TypeDefinition dependencies. So, we can remove `@types/glob`.
Please see: https://github.com/isaacs/node-glob/blob/v9/changelog.md#90
refs: https://github.com/microsoft/vscode-docs/pull/7125
-----
Thank you :)
> chore(deps): update `glob` and remove `@types/glob`

- CHANGELOG.md
- README.md
- lib/download.test.ts
- lib/download.ts
- lib/index.ts
- lib/runTest.ts
- lib/util.ts
- package.json
- sample/.github/workflows/ci.yml
- sample/src/test/runTest.ts
> feat: runVSCodeCommand as workaround for CVE-2024-27980

- pipeline.yml
- sample/package.json
- sample/yarn.lock
Fixes compatibility issues with version bumps in the last PR. We're good to use Node 20 to lint and such, just switch to the min version (16) for running tests. This is needed to publish.
> fix: compile with node 20, test with 16

- CHANGELOG.md
- lib/index.ts
- lib/runTest.ts
Refs https://github.com/microsoft/vscode-test-cli/issues/44
> fix: throw a well-typed error on run failure

- README.md
The Github Actions link was pointing to a non existent Travis sample. This has been corrected to point to the Github Actions sample.
> docs: update Github Actions link to point to sample

- lib/download.ts
Added a line that ensures `extractDir` exists before attempting to unzip to it on macOS and Linux platforms. On macOS version 15.3.2, `unzip` does not create intermediate directories. Based on some [brief research](https://askubuntu.com/questions/1155509/is-it-possible-to-unzip-documents-into-a-directory-which-is-created-on-the-fly-i), this seems to be the case for at least some Linux varieties as well.
This was causing an `Invalid extraction directory` error to occur every time I tried to debug a VSCode extension using the test-cli. The error occurs even for a freshly made project using `npx --package yo --package generator-code -- yo code`:
```console
steven@MacBookPro vscode-unzip-test % npx vscode-test
✔ Validated version: 1.98.2
✔ Found at …
```
> fix: avoid 'Invalid extraction directory' when unzipping
